WIDTH=800
HEIGHT=800
TEXT_IMPORTANT = "IMPORTANT"
TEXT_URGENT = "URGENT"
TEXT_NOT_IMPORTANT = "NOT IMPORTANT"
TEXT_NOT_URGENT = "NOT URGENT"
TEXT_IMPORTANT_NOT_URGENT = TEXT_IMPORTANT + " + " + TEXT_NOT_URGENT
TEXT_NOT_IMPORTANT_URGENT = TEXT_NOT_IMPORTANT + " + " + TEXT_URGENT
TEXT_NOT_MIX = TEXT_NOT_IMPORTANT + " + " + TEXT_NOT_URGENT
TEXT_MIX = TEXT_IMPORTANT + " + " + TEXT_URGENT
TEXT_LIST = [TEXT_NOT_MIX, TEXT_NOT_IMPORTANT_URGENT, TEXT_IMPORTANT_NOT_URGENT, TEXT_MIX]

IMPORTANT, URGENT, NOT_URGENT, NOT_IMPORTANT = ["important"], ["urgent"], ["not urgent"], ["not important"]
MATRIX = [
            [],
            [],
            [],
            []
        ]
